### PR TITLE
fix comment symbols

### PR DESCRIPTION
**Pull request by guyskk**
This support `ctrl + /` to toggle comments in mako http://docs.makotemplates.org/en/latest/syntax.html#comments

### CODE REVIEW

**Comment by guyskk** [comment]
ping @tommorris

**Comment by tommorris** [comment]
Hi @guyskk: thanks for the contribution. I'm going to try and test this and release this later this week.

**Comment by tommorris** [comment]
Just tested. Works great. Thanks again, @guyskk.

**Comment by tommorris** [comment]
Released in v0.2.0

**Comment by guyskk** [comment]
Great, thank you!

**Pull request merged**
